apiVersion: v1
kind: PersistentVolume
metadata:
  name: certbot-volume
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/certbot
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpression:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node